version: '3'

dotenv: ['.env']

tasks:
  cmd:api:
    desc: Запуск API
    ignore_error: true
    cmd: go run -tags "sqlite_fts5" ./cmd/api -m ./migrations
  
  cmd:preloader:
    desc: Запуск предзагрузщика места
    ignore_error: true
    cmd: go run ./cmd/preloader

  k6:check-authorizations:
    cmd: k6 run -e API_URL=http://localhost:8080 ./scripts/k6/check-authorizations.js

  k6:booking:
    cmd: k6 run -e API_URL=http://localhost:8080 ./scripts/k6/booking.js

  migrate:create:
    desc: |
      Создание новой миграции (usage: task migrate:create -- название_миграции)
    cmd: migrate create -ext sql -dir migrations -tz Asia/Almaty {{.CLI_ARGS}}
