// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"time"
)

type User struct {
	UserID        int64
	Email         string
	PasswordHash  string
	PasswordPlain *string
	FirstName     string
	Surname       string
	Birthday      *string
	RegisteredAt  time.Time
	IsActive      bool
	LastLoggedIn  time.Time
}
