// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"time"
)

type Booking struct {
	ID      int64
	UserID  int64
	EventID int64
	Status  string
}

type BookingOrder struct {
	ID        int64
	BookingID int64
	OrderID   string
	Status    *string
}

type BookingPayment struct {
	ID        int64
	BookingID int64
	OrderID   string
	Status    *string
	PaymentID string
	Amount    int64
	Currency  string
	TeamSlug  string
}

type Seat struct {
	ID         int64
	EventID    int64
	ExternalID *string
	Row        int64
	Number     int64
	Price      string
	Status     string
}

type User struct {
	UserID        int64
	Email         string
	PasswordHash  string
	PasswordPlain *string
	FirstName     string
	Surname       string
	Birthday      *string
	RegisteredAt  time.Time
	IsActive      bool
	LastLoggedIn  time.Time
}
