// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetBookings(ctx context.Context, userID int64) ([]GetBookingsRow, error)
}

var _ Querier = (*Queries)(nil)
