// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: seats.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getSeats = `-- name: GetSeats :many
select
  id, event_id, external_id, "row", number, price, status
from seats s
where 1=1
  and ?1 = s.event_id
  and (
    ?2 = s.row 
    or ?2 is null
  )
  and (
    ?3 = s.status
    or ?3 is null
  )
limit ?5
offset ?4
`

type GetSeatsParams struct {
	EventID int64
	Row     sql.NullInt64
	Status  *string
	Offset  int64
	Limit   int64
}

func (q *Queries) GetSeats(ctx context.Context, arg GetSeatsParams) ([]Seat, error) {
	rows, err := q.db.QueryContext(ctx, getSeats,
		arg.EventID,
		arg.Row,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Seat
	for rows.Next() {
		var i Seat
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ExternalID,
			&i.Row,
			&i.Number,
			&i.Price,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
