// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"
)

const getUser = `-- name: GetUser :one
select
    user_id, email, password_hash, password_plain, first_name, surname, birthday, registered_at, is_active, last_logged_in
from users u
where 1=1
    and u.email = ?1
`

func (q *Queries) GetUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordPlain,
		&i.FirstName,
		&i.Surname,
		&i.Birthday,
		&i.RegisteredAt,
		&i.IsActive,
		&i.LastLoggedIn,
	)
	return i, err
}
