-- Remove token generation fields
-- SQLite doesn't support dropping columns directly in older versions
-- This would require recreating the table, but for development we can leave it
-- ALTER TABLE booking_payments DROP COLUMN amount;
-- ALTER TABLE booking_payments DROP COLUMN currency;
-- ALTER TABLE booking_payments DROP COLUMN team_slug;